homeassistant:
  # Name of the location where Home Assistant is running
  name: Brooklyn, NY
  # Location required to calculate the time the sun rises and sets
  latitude: 
  longitude: 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: Imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Notifications
notify:
  - name: hass
    platform: pushbullet
    api_key: *

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: Weather
    monitored_conditions:
      - temperature
      - symbol

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# abode home security
abode:
  username: 
  password: 
  name: Abode Alarm System

# HTTP
http:
  api_password:

# MQTT
mqtt:
  broker: m14.cloudmqtt.com
  port: 14221
  username: 
  password: 
  client_id: 

device_tracker:
  - platform: owntracks
  - platform: nmap_tracker
    consider_home: 1500
    track_new_devices: false
    hosts:
      - 192.168.1.0/24

# Zones
zone:
  - name: Jet.com
    latitude: 
    longitude: 
    radius: 350
    icon: mdi:briefcase
  - name: Home
    latitude: 
    longitude: 
    radius: 350
    icon: mdi:home

# Switches
switch:
  - platform: vesync
    username: 
    password: 

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
